apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      env: production-php
  template:
    metadata:
      name: php-pod
      labels:
        env: production-php
    spec:
      volumes:
        - name: php-vol
          persistentVolumeClaim:
            claimName: php-pvc
      containers:
      - name: php
        image: ldamasio/vtiger:1
        volumeMounts:
          - mountPath: /var/www/html
            name: php-vol


